custom_rules:
    # avoid public/open APIs with @escaping closures; prefer delegate, actor, or view model objects
    no_public_escaping_functions:
        name: "no public escaping functions"
        message: "avoid public/open APIs with @escaping closures; prefer delegate, actor, or view model objects"
        regex: "(public|open)\\s+(func|init)\\s+[^(]*\\([^)]*@escaping"
        severity: error

    # public protocols should not expose @escaping closures; use delegate/actor types instead
    no_public_protocol_escaping_closures:
        name: "no public protocol escaping closures"
        message: "public protocols should not expose @escaping closures; use delegate/actor types instead"
        regex: "(public|open)\\s+protocol\\s+[^{]*\\{[^}]*@escaping"
        severity: error

    # avoid AnyView/type erasure; prefer concrete view types
    swift_warn_anyview:
        name: "avoid AnyView"
        message: "avoid AnyView/type erasure; prefer concrete view types"
        regex: "\\bAnyView\\b"
        severity: warning

    no_manual_nserror:
        name: "no manual NSError"
        message: "avoid manual NSError; use a typed Error or LocalizedError"
        regex: "\\bNSError\\s*\\("
        severity: error

opt_in_rules:
    - array_init
    - balanced_xctest_lifecycle
    - contains_over_first_not_nil
    - contains_over_filter_is_empty
    - discouraged_object_literal
    - empty_string
    - explicit_init
    - first_where
    - implicit_return
    - overridden_super_call
    - prefer_self_type_over_type_of_self
    - pattern_matching_keywords
    - redundant_nil_coalescing
    - redundant_type_annotation
    - return_value_from_void_function
    - large_tuple
    - toggle_bool
    - unused_optional_binding
    - yoda_condition
    - private_swiftui_state
    - weak_delegate

included:
    - ios/B90HQ
    - ios/Library
    - ios/B90HQTests

excluded:
    - ios/B90HQ/_generated
    - ios/DerivedData

# we disable mist default formatting rules since we handle formatting via swiftformat
# and we want to avoid conflicts between swiftlint and swiftformat
disabled_rules:
    - force_cast
    - force_try
    - closure_parameter_position
    - closure_spacing
    - collection_alignment
    - empty_count
    - for_where
    - multiple_closures_with_trailing_closure
    - nesting
    - notification_center_detachment
    - operator_usage_whitespace
    - shorthand_operator
    - todo
    - literal_expression_end_indentation
    - sorted_imports
    - static_operator
    - trailing_comma
    - unavailable_condition
    - unavailable_function
    - vertical_whitespace_between_cases
    - switch_case_alignment
    - identifier_name
    - type_name
    - file_length
    - line_length
    - type_body_length
    - function_body_length
    - function_parameter_count
cyclomatic_complexity:
    warning: 20
    error: 30
    ignores_case_statements: true
