name: SwiftUIStarter
options:
    bundleIdPrefix: com.example
    deploymentTarget:
        iOS: "17.0"

targets:
    SwiftUIStarter:
        type: application
        platform: iOS
        sources: [SwiftUIStarter]
        bundleId: com.example.SwiftUIStarter
        settings:
            base:
                INFOPLIST_FILE: SwiftUIStarter/Info.plist
                PRODUCT_BUNDLE_IDENTIFIER: com.example.SwiftUIStarter

                DEVELOPMENT_TEAM: <YOUR_DEVELOPMENT_TEAM_ID>
                CODE_SIGN_STYLE: Automatic
                CODE_SIGN_IDENTITY: "Apple Development"
                
                TARGETED_DEVICE_FAMILY: 1
                ENABLE_USER_SCRIPT_SANDBOXING: NO
            
